### ISSUE TITLE
Can't compile fbff correctly on Debian 

### ISSUE THREAD

**Issue by Nanodragon999** [aligrudi/fbff#2]
Hello

So i can't seem to compile fbff correctly,and from what i understand,it all come down to ffmpeg,though correctly if i'am wrong :)

here the error output for ffmpeg,version 3.2.3 (since i seen in one of your commit that you added support for it)
```
$ make
cc -o fbff fbff.o ffs.o draw.o -L/opt/lib -lavutil -lavformat -lavcodec -lavutil -lswscale -lswresample -lz -lm -lpthread
//usr/local/lib/libavformat.a(rtsp.o): In function `ff_rtsp_connect':
/home/npower10/etc/bin/ffmpeg-3.2.3/libavformat/rtsp.c:1660: undefined reference to `ff_log2_tab'
//usr/local/lib/libavformat.a(matroskadec.o): In function `ebml_read_num':
/home/npower10/etc/bin/ffmpeg-3.2.3/libavformat/matroskadec.c:820: undefined reference to `ff_log2_tab'
/home/npower10/etc/bin/ffmpeg-3.2.3/libavformat/matroskadec.c:820: undefined reference to `ff_log2_tab'
//usr/local/lib/libavformat.a(rtpenc_vc2hq.o): In function `get_interleaved_ue_golomb':
/home/npower10/etc/bin/ffmpeg-3.2.3/./libavcodec/golomb.h:142: undefined reference to `ff_interleaved_dirac_golomb_vlc_code'
//usr/local/lib/libavformat.a(rtpenc_vc2hq.o): In function `init_get_bits':
/home/npower10/etc/bin/ffmpeg-3.2.3/./libavcodec/get_bits.h:426: undefined reference to `ff_interleaved_golomb_vlc_len'
//usr/local/lib/libavformat.a(rtpenc_vc2hq.o): In function `get_interleaved_ue_golomb':
/home/npower10/etc/bin/ffmpeg-3.2.3/./libavcodec/golomb.h:142: undefined reference to `ff_interleaved_dirac_golomb_vlc_code'
/home/npower10/etc/bin/ffmpeg-3.2.3/./libavcodec/golomb.h:130: undefined reference to `ff_interleaved_dirac_golomb_vlc_code'
/home/npower10/etc/bin/ffmpeg-3.2.3/./libavcodec/golomb.h:142: undefined reference to `ff_interleaved_dirac_golomb_vlc_code'
/home/npower10/etc/bin/ffmpeg-3.2.3/./libavcodec/golomb.h:130: undefined reference to `ff_interleaved_dirac_golomb_vlc_code'
/home/npower10/etc/bin/ffmpeg-3.2.3/./libavcodec/golomb.h:130: undefined reference to `ff_interleaved_dirac_golomb_vlc_code'
//usr/local/lib/libavformat.a(rtpenc_vc2hq.o):/home/npower10/etc/bin/ffmpeg-3.2.3/./libavcodec/golomb.h:142: more undefined references to `ff_interleaved_dirac_golomb_vlc_code' follow
//usr/local/lib/libavformat.a(rtpenc_vc2hq.o): In function `get_interleaved_ue_golomb':
/home/npower10/etc/bin/ffmpeg-3.2.3/./libavcodec/golomb.h:128: undefined reference to `ff_interleaved_ue_golomb_vlc_code'
/home/npower10/etc/bin/ffmpeg-3.2.3/./libavcodec/golomb.h:128: undefined reference to `ff_interleaved_ue_golomb_vlc_code'
/home/npower10/etc/bin/ffmpeg-3.2.3/./libavcodec/golomb.h:128: undefined reference to `ff_interleaved_ue_golomb_vlc_code'
collect2: error: ld returned 1 exit status
Makefile:11: recipe for target 'fbff' failed
make: *** [fbff] Error 1 ```

and that's just for the version 3.2.3,which i thought would work since you mentioned that you added support for it.
Need to be noted however,that i tried near all version of ffmpeg,from 3.2.3 to the latest,which is 4.0.1 at the moment of writing.Of course,i also noted that all the newer version output more error message when compiled with fbff than the older ones.

I'm running Debian Testing branch and use the latest package available.
I think it is very intriguing that the latest version output more errors than the older one,considering that fbff can be found on the AUR,for Arch Linux and supposedly work as expected.

Best regards,N.

PS:i found earlier a version of ffmpeg that,once compiled,output the least error out of all the one i tried with fbff ```
$ make
cc -o fbff fbff.o ffs.o draw.o -L/opt/lib -lavutil -lavformat -lavcodec -lavutil -lswscale -lswresample -lz -lm -lpthread
//usr/local/lib/libavformat.a(rtsp.o): In function `ff_rtsp_connect':
/home/npower10/etc/bin/ffmpeg-3.0.1/libavformat/rtsp.c:1653: undefined reference to `ff_log2_tab'
//usr/local/lib/libavformat.a(matroskadec.o): In function `ebml_read_num':
/home/npower10/etc/bin/ffmpeg-3.0.1/libavformat/matroskadec.c:745: undefined reference to `ff_log2_tab'
/home/npower10/etc/bin/ffmpeg-3.0.1/libavformat/matroskadec.c:745: undefined reference to `ff_log2_tab'
collect2: error: ld returned 1 exit status
Makefile:11: recipe for target 'fbff' failed
make: *** [fbff] Error 1
```
this is ffmpeg version 3.0.1 btw

**Comment by Nanodragon999** [comment]
Never-mind,i managed to compile ffmpeg correctly,and the previous error are irrelevant :+1: 

But,i still get some error after a successful compilation of fbff.

```[NULL @ 0x81205bc0] No codec provided to avcodec_open2()```
```[NULL @ 0x8129d540] No codec provided to avcodec_open2() ```

this was when i tried playing a .mp4 file with a m4a audio stream.
there different error depending on the extensions/types,here a rundown of the more popular : 

```[NULL @ 0x805774c0] No codec provided to avcodec_open2()```
for a m4a file,audio only of course

```[NULL @ 0x80ebc6c0] No codec provided to avcodec_open2()```
this is for a .wav file.

```[NULL @ 0x811cd900] No codec provided to avcodec_open2()```
for a .avi file.

and so on,so forth.
I'm totally aware fbff should be used mainly for viewing videos,not audio file,but knowing it use ffmpeg,it could be possible,as i didn't yet see how it work.

**Comment by aligrudi** [comment]
Norton <notifications@github.com> wrote:
> Never-mind,i managed to compile ffmpeg correctly,and the previous error are irrelevant :+1: 

I did try to reproduce the problem on ffmpeg 3.* and 4.0.1 but failed.
Happy to hear that it is solved.

> But,i still get some error after a successful compilation of fbff.
> 
> ```[NULL @ 0x811cd900] No codec provided to avcodec_open2()
> ```
> for a .avi file.

Can ffplay play it?

> and so on,so forth.
> I'm totally aware fbff should be used mainly for viewing videos,not audio file,but knowing it use ffmpeg,it could be possible,as i didn't yet see how it work.

Try -v- to disable the video.  -a and -v options select audio/video
streams to play, if the file has more than one.

**Comment by Nanodragon999** [comment]
Thank you for your replies,

I tried different combination with the -v- and -a -v option,but it still reproduce the same error,except on some time,when it doesn't output any error or even open the video.

Could you give me an example ? maybe with this video sample ?  
http://www.engr.colostate.edu/me/facil/dynamics/avis.htm

I think those are open source,so it should be ok to test it on those :) (correct me if i'm wrong)

I tried the following combination:
```$ fbff -a alsa  Downloads/flame.avi ```
```[NULL @ 0x81665900] No codec provided to avcodec_open2() ```

```$ fbff -a alsa -v vdpau Downloads/flame.avi```
```[NULL @ 0x813f0900] No codec provided to avcodec_open2()```

with no success whatsoever.

Regard,N.

EDIT: By the way,those videos work fine on mpv/mplayer,as well as other player.
EDIT 2:here an example of when there no error but it still don't open the videos:
```$ fbff -v- -a -v Downloads/flame.avi```
No error,but no video/audio output either.

**Comment by aligrudi** [comment]
Norton <notifications@github.com> wrote:
> Could you give me an example ? maybe with this video sample ?  
> http://www.engr.colostate.edu/me/facil/dynamics/avis.htm
> 
> I think those are open source,so it should be ok to test it on those :) (correct me if i'm wrong)

They play fine here.  However, since fbff synchronizes video
to audio and these vidoes have no sound, they play very fast.
Try this patch for a ~24fps playback (when there is no sound).

diff --git a/fbff.c b/fbff.c
index 5c6af24..f6097ef 100644
--- a/fbff.c
+++ b/fbff.c
@@ -387,6 +387,7 @@ static void mainloop(void)
 			int ignore = jump && (vnum % (jump + 1));
 			void *buf;
 			int ret = ffs_vdec(vffs, ignore ? NULL : &buf);
+			usleep(1000000 / 24);
 			vnum++;
 			if (ret < 0)
 				eof++;

My FFMPEG version and compilation options:

ffmpeg version 4.0.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (CRUX-x86_64-multilib)
  configuration: --enable-libfreetype --enable-openssl --enable-nonfree --prefix=/usr --disable-debug --disable-doc --enable-gpl --enable-version3 --enable-shared --enable-pic --enable-ffplay --enable-avfilter --enable-postproc --disable-pthreads --disable-static --enable-swresample
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100


> I tried the following combination:
> ```$ fbff -a alsa  Downloads/flame.avi ```

Note that after -a and -v either an integer or a - should
appear.

**Comment by Nanodragon999** [comment]
Thanks for your replies :) ,

Successful compilation of both FFMPEG and FBFF,with the same version and compilation options you posted above :+1:  and all the other errors above are now irrelevant :100: 

BUT,i still got some error on my part: 
```fbff: /dev/dsp busy?```
So,i made a little research,and i just needed to do:
```apt-get install alsa-oss```
```modprobe snd_pcm_oss```
```modprobe snd_mixer_oss```

and IT FINALLY WORKED !

I can't Thank you enough for all your help,since i passed a whole week trying to figure this all out on my own,before opening an issue.
